package models

import (
	"time"

	"gorm.io/gorm"
)

// Notification types. These identify what application event produced a
// notification so the frontend can group or icon them consistently and so the
// backend has a single source of truth for the values it stores.
const (
	NotificationTypeCertificate  = "certificate"
	NotificationTypeCredits      = "credits"
	NotificationTypeEnrollment   = "enrollment"
	NotificationTypeActivity     = "activity"
	NotificationTypeNotice       = "notice"
	NotificationTypeAnnouncement = "announcement"
	NotificationTypeGeneral      = "general"
)

// Notification titles that more than one package has to agree on. An
// activity-monitoring reminder is written by the reminder endpoint and
// recognised by the backfill migration that lifts pre-existing reminders out of
// the admin-note trail, so the two must not drift apart.
const (
	NotificationTitleActivityReminder = "Activity Reminder"
	NotificationTitleNewActivity      = "New Activity"
)

// Notification is a persistent, per-student message generated by application
// events (certificate decisions, enrolments, admin notices, announcements...).
// It is owned by the student identified by StudentRollNo, mirroring how
// Certificate and Enrollment reference the student primary key.
type Notification struct {
	ID            uint           `gorm:"primaryKey" json:"id"`
	StudentRollNo string         `gorm:"type:varchar(50);not null;index" json:"student_roll_no"`
	Student       Student        `gorm:"foreignKey:StudentRollNo;references:RollNo" json:"-"`
	Title         string         `gorm:"type:varchar(200);not null" json:"title"`
	Message       string         `gorm:"type:text" json:"message"`
	Type          string         `gorm:"type:varchar(50);not null;default:'general';index" json:"type"`
	IsRead        bool           `gorm:"not null;default:false;index" json:"is_read"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"index" json:"-"`
}
